// src/components/Toasty.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { fly } from 'svelte/transition'

  import toastyMp3 from '/audio/toasty.mp3'
  import toastyImage from '/images/toasty.png'

  let toasty: boolean = false

  onMount(() => {
    let konamiCodeArray: Array<string> = []
    const konamiCodeKey: string =
      'ArrowUp,ArrowUp,ArrowDown,ArrowDown,ArrowLeft,ArrowRight,ArrowLeft,ArrowRight,KeyB,KeyA'
    const toastyAudio = <HTMLVideoElement>(
      document.getElementById('js-toasty-audio')
    )

    document.addEventListener('keydown', event => {
      konamiCodeArray.push(event.code)
      if (konamiCodeArray.toString().indexOf(konamiCodeKey) >= 0) {
        toastyAudio.load()
        toastyAudio.play()
        konamiCodeArray = []
        toasty = true
      }
    })
  })
</script>

<input
  type="checkbox"
  bind:checked={toasty}
  class={`sr-only ${
    toasty ? 'bg-red' : 'bg-blue'
  } appearance-none w-4 h-4 block`}
/>

{#if toasty}
  <img
    src={toastyImage}
    alt="Toasty"
    class="toasty"
    in:fly={{ x: 200, duration: 300 }}
    out:fly={{ delay: 200, x: 200, duration: 400 }}
    on:introend={() => (toasty = false)}
  />
{/if}

<audio id="js-toasty-audio">
  <source src={toastyMp3} type="audio/mp3" />
</audio>

<style lang="postcss">
  .toasty {
    @apply fixed bottom-0 right-0 z-10 h-[12.5rem] w-[12.5rem];
  }
</style>

// src/components/Toasty.tsx
// import * as React from 'react'
import { useState, useEffect } from 'react'

import toastyMp3 from '/audio/toasty.mp3'
import toastyImage from '/images/toasty.png'

export default function Toasty() {
  const [toasty, setToasty] = useState(false)

  useEffect(() => {
    let konamiCodeArray: Array<string> = []
    const konamiCodeKey: string =
      'ArrowUp,ArrowUp,ArrowDown,ArrowDown,ArrowLeft,ArrowRight,ArrowLeft,ArrowRight,KeyB,KeyA'

    const toastyAudio = document.getElementById('js-toasty-audio')

    document.addEventListener('keydown', e => {
      konamiCodeArray.push(e.code)

      console.log(konamiCodeArray)

      if (konamiCodeArray.toString().indexOf(konamiCodeKey) >= 0) {
        toastyAudio.load()
        toastyAudio.play()
        konamiCodeArray = []
        setToasty(true)
      }
    })
  })

  return (
    <>
      <img
        src={toastyImage}
        alt="Toasty"
        className="fixed bottom-0 -right-full z-10 h-[12.5rem] w-[12.5rem]"
      />

      <audio id="js-toasty-audio">
        <source src={toastyMp3} type="audio/mp3" />
      </audio>
    </>
  )
}
